config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'searches#index'

  resources :searches

  resources :drugs do
    resources :diseases
    resources :genes
  end
  resources :diseases do
    resources :genes
    resources :drugs
  end
  resources :genes do
    resources :diseases
    resources :drugs
  end
end

app/models/drug.rb
class Drug < ActiveRecord::Base
  establish_connection :pgx

  self.table_name = 'drug'

  alias_attribute :drugbank, :drugbankID
  alias_attribute :pharmgkb, :pharmGkbID

  include Searcheable
  include LinkData
  include ExportableToTsv
  include ServiceUrls

  has_many :drug_disease_links,
           foreign_key: 'id_obj1'
  has_many :diseases,
           -> { select('disease.*, link.isCurated, link.PMIDs').order('link.isCurated DESC') },
           through: :drug_disease_links,
           inverse_of: :drugs

  has_many :drug_gene_links,
           foreign_key: 'id_obj2'
  has_many :genes,
           -> { select('gene.*, link.isCurated, link.PMIDs').order('link.isCurated DESC') },
           through: :drug_gene_links,
           inverse_of: :drugs
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: [:show, :edit, :update, :destroy]
  include SearchesHelper

  def index
    drugs_smart_listing(params[:drugs_filter])
  end

  def show
    diseases_for_drug_smart_listing(params[:diseases_filter], @drug.id)
  end

  private
    def set_drug
      @drug = Drug.find(params[:id])
    end

    def drug_params
      params.require(:drugs).permit(:disease_page, :gene_page, :name, :description, :source, :drugbankID, :pharmGkbID, :fdaApproved)
    end
end

app/helpers/drugs_helper.rb
module DrugsHelper
  def arel_for_drug(_filter)
    # t = Drug.arel_table
    #
    # r = t['drug_id'].eq(0)
    # r = r.or(t[:name].matches("%#{filter}%"))
    # r = r.or(t[:description].matches("%#{filter}%"))

    Drug.none
  end
end

app/views/drugs/_drug.haml
%tr
  %td= link_to(drug.name, drug_path(drug))
  %td= drug['description']
  %td= attr_link(:drugbank, drug)
  %td
    %a{href: "http://www.pharmgkb.org/drug/#{drug['pharmGkbID']}"}
      = drug['pharmGkbID']
  %td
    - if drug['fdaApproved']
      %span.label.label-success
        approved
    - else
      %span.label.label-danger
        non-approved

  %td= drug['source']
  - if drug.ld?
    %td
      = render 'common/pmids', locals: {pmids: drug.pmids}
    %td
      = render 'common/curated', locals: {status: drug.curated?}

app/views/drugs/_list.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %th.col-md-3= "Name"
      %th.col-md-3= "Description"
      %th.col-md-4= "Source"
    %tbody
      - smart_listing.collection.each do |drug|
        = render drug

  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  %i.fa.fa-frown-o.fa-5x

app/views/drugs/_smart_list.haml
= smart_listing_render :drugs

app/views/drugs/_smart_list_search_form.haml
= smart_listing_controls_for(:drugs, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :drugs_filter, '', class: "search form-control",
                              placeholder: "Search...", autocomplete: :off

app/views/drugs/_smart_list_with_search.haml
= render 'drugs/smart_list_search_form'
= render 'drugs/smart_list'

app/views/drugs/index.haml
= render 'drugs/smart_list_with_search'

app/views/drugs/index.js.erb
<%= smart_listing_update :drugs %>

app/views/drugs/show.haml
%p#notice= notice

%h1.center
  Drug

%table.table.table-bordered.table-responsive.table-striped.drug-desc
  %tr
    %td
      %b
        Name
    %td= @drug.name
  %tr
    %td
      %b
        Description
    %td= @drug.description
  %tr
    %td
      %b
        Drugbankid
    %td
      %a{href: "http://www.drugbank.ca/drugs/#{@drug.drugbankID}"}
        = @drug.drugbankID
  %tr
    %td
      %b
        Pharmgkbid
    %td
      %a{href: "http://www.pharmgkb.org/drug/#{@drug.pharmGkbID}"}
        = @drug.pharmGkbID
  %tr
    %td
      %b
        FDA approved
    %td
      - if @drug.fdaApproved
        %span.label.label-success
          approved
      - else
        %span.label.label-danger
          non-approved
  %tr
    %td
      %b
        Source
    %td= @drug.source

= render 'diseases/smart_list_with_search'

app/views/drugs/show.js.erb
<%= smart_listing_update :diseases %>