config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'searches#index'

  resources :searches

  resources :drugs do
    resources :diseases
    resources :genes
  end
  resources :diseases do
    resources :genes
    resources :drugs
  end
  resources :genes do
    resources :diseases
    resources :drugs
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  def genes(page=1)
    @genes ||= find_genes(page)
  end

  def drugs(page=1)
    @drugs ||= find_drugs(page)
  end

  def diseases(page=1)
    @diseases ||= find_diseases(page)
  end

  private

  def find_genes(page)
    f = YAML.load(gene_fields).select{|v| v != ''}
    if f.empty?
      Gene.none
    else
      t = Gene.arel_table

      r = t['gene_id'].eq(0)
      r = r.or(t[:name].matches("%#{keywords}%")) if f.include?('name')
      r = r.or(t[:description].matches("%#{keywords}%")) if f.include?('description')
      r = r.or(t[:uniprotKB].matches("%#{keywords}%")) if f.include?('uniprotKB')
      r = r.or(t[:entrezid].eq("#{keywords}")) if f.include?('entrezID')

      Gene.where(r)
          .order(:gene_id)
    end
  end

  def find_drugs(page)
    f = YAML.load(drug_fields).select{|v| v != ''}
    if f.empty?
      Drug.none
    else
      t = Drug.arel_table

      r = t['drug_id'].eq(0)
      r = r.or(t[:name].matches("%#{keywords}%")) if f.include?('name')
      r = r.or(t[:drugbankID].matches("%#{keywords}%")) if f.include?('drugbankID')

      Drug.where(r)
          .order(:drug_id)
    end
  end

  def find_diseases(page)
    f = YAML.load(disease_fields).select{|v| v != ''}
    if f.empty?
      Disease.none
    else
      t = Disease.arel_table

      r = t['disease_id'].eq(0)
      r = r.or(t[:name].matches("%#{keywords}%")) if f.include?('name')
      r = r.or(t[:alt_names].matches("%#{keywords}%")) if f.include?('alt_names')

      Disease.where(r)
             .order(:disease_id)
    end
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include SearchesHelper

  def index
    diseases_smart_listing(params[:query])
    genes_smart_listing(params[:query])
    drugs_smart_listing(params[:query])
  end

  private

  def user_params
    params.require(:search).permit(:filter)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
  include DiseasesHelper
  include GenesHelper
  include DrugsHelper

  def simple_query(klass:, filter:, all: true)
    k = Object.const_get(klass.capitalize)

    if filter
      # query = send("arel_for_#{klass}", filter)
      # k.where(query)
      # send("arel_for_#{klass}", filter)
      # k.where('id < 3')
      Gene.__elasticsearch__.search(query: { match: { name: filter } }).records
    elsif all
      k.all
    else
      k.none
    end
  end

  def gene_query(query)
    if query
      Gene.__elasticsearch__.search(query: { match: { name: query } }).records
    else
      Gene.none
    end
  end

  def dependant_query(base_class:, base_id:, deps_class:, filter:)
    k = Object.const_get(base_class.capitalize)

    if filter
      query = send("arel_for_#{deps_class}", filter)
      k.find(base_id)
        .send(deps_class.pluralize)
        .where(query)
    else
      k.find(base_id)
        .send(deps_class.pluralize)
        .all
    end
  end

  def diseases_for_gene_smart_listing(filter, gene_id)
    diseases_scope =
      dependant_query(base_class: 'gene', base_id: gene_id, deps_class: 'disease', filter: filter)
    @diseases = smart_listing_create(:diseases, diseases_scope, partial: 'diseases/list')
  end

  def diseases_for_drug_smart_listing(filter, drug_id)
    diseases_scope =
      dependant_query(base_class: 'drug', base_id: drug_id, deps_class: 'disease', filter: filter)
    @diseases = smart_listing_create(:diseases, diseases_scope, partial: 'diseases/list')
  end

  def genes_for_disease_smart_listing(filter, disease_id)
    genes_scope =
      dependant_query(base_class: 'disease', base_id: disease_id, deps_class: 'gene', filter: filter)
    @genes = smart_listing_create(:genes, genes_scope, partial: 'genes/list')
  end

  def diseases_smart_listing(query)
    diseases_scope = simple_query(klass: 'disease', filter: query)
    @diseases = smart_listing_create(:diseases, Disease.none, partial: 'diseases/list')
  end

  def genes_smart_listing(query)
    # genes_scope = simple_query(klass: 'gene', filter: query)
    # @genes = smart_listing_create(:genes, genes_scope, partial: 'genes/list')
    @genes = smart_listing_create(:genes, gene_query(query), partial: 'genes/list')
  end

  def drugs_smart_listing(query)
    drugs_scope = simple_query(klass: 'drug', filter: query)
    @drugs = smart_listing_create(:drugs, Drug.none, partial: 'drugs/list')
  end
end

app/views/searches/_list.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %th.col-md-3= "Name"
      %th.col-md-3= "Type"
    %tbody
      - smart_listing.collection.each do |o|
        %tr
          %td
            = link_for_object(o)
          %td= o.class.to_s

  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links

app/views/searches/_smart_list.haml
= smart_listing_controls_for(:hits, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :filter, '', class: "search form-control", 
                              placeholder: "Search...", autocomplete: :off

= smart_listing_render :hits

app/views/searches/index.haml
.row.search
  .col-sm-8.col-sm-offset-2
    = form_tag(searches_path, remote: true, method: :get, role: :form) do
      .input-group
      = text_field_tag(:query, params[:query], class: 'form-control input-sm', autofocus: '')


%ul.nav.nav-tabs
  - unless @genes.nil?
    %li{class: "#{'not-empty' if @genes.count > 0}"}
      %a{href: '#genes', 'data-toggle' => 'tab'}
        Genes
        #genes_count= @genes.total_count

  - unless @diseases.nil?
    %li{class: "#{'not-empty' if @diseases.count > 0}"}
      %a{href: '#diseases', 'data-toggle' => 'tab'}
        Diseases
        #diseases_count= @diseases.total_count

  - unless @drugs.nil?
    %li{class: "#{'not-empty' if @drugs.count > 0}"}
      %a{href: '#drugs', 'data-toggle' => 'tab'}
        Drugs
        #drugs_count= @drugs.total_count


.tab-content
  - unless @genes.nil?
    #genes.tab-pane.fade
      = render 'genes/smart_list'
  - unless @diseases.nil?
    #diseases.tab-pane.fade
      = render 'diseases/smart_list'
  - unless @drugs.nil?
    #drugs.tab-pane.fade
      = render 'drugs/smart_list'

app/views/searches/index.js.erb
<%= smart_listing_update :genes %>
<%= smart_listing_update :diseases %>
<%= smart_listing_update :drugs %>
$('#genes_count').html(<%= @genes.total_count %>)
$('#diseases_count').html(<%= @diseases.total_count %>)
$('#drugs_count').html(<%= @drugs.total_count %>)

app/views/searches/new.haml
%h1
  Search

- form_for @search do |f|
  .field
    = f.label :keywords
    %br/
    = f.text_field :keywords