config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'searches#index'

  resources :searches

  resources :drugs do
    resources :diseases
    resources :genes
  end
  resources :diseases do
    resources :genes
    resources :drugs
  end
  resources :genes do
    resources :diseases
    resources :drugs
  end
end

app/models/gene.rb
class Gene < ActiveRecord::Base
  establish_connection :pgx

  self.table_name = 'gene'

  alias_attribute :uniprot, :uniprotKB
  alias_attribute :ensembl, :ensemblID
  alias_attribute :entrez,  :entrezID
  alias_attribute :pharmgkb, :pharmGkbID

  include Searcheable
  include LinkData
  include ExportableToTsv
  include ServiceUrls

  has_many :drug_gene_links,
           foreign_key: 'id_obj1'
  has_many :drugs,
           -> { select('drug.*, link.isCurated, link.PMIDs').order('link.isCurated DESC').order('fdaApproved DESC') },
           through: :drug_gene_links,
           inverse_of: :genes

  has_many :disease_gene_links,
           foreign_key: 'id_obj1'
  has_many :diseases,
           -> { select('disease.*, link.isCurated, link.PMIDs').order('link.isCurated DESC') },
           through: :disease_gene_links,
           inverse_of: :genes
end

app/controllers/genes_controller.rb
class GenesController < ApplicationController
  before_action :set_gene, only: [:show, :edit, :update, :destroy]
  include SearchesHelper

  def index
    genes_smart_listing(params[:genes_filter])
  end

  def show
    diseases_for_gene_smart_listing(params[:diseases_filter], @gene.id)
  end

  private

  def set_gene
    @gene = Gene.find(params[:id])
  end

  def gene_params
    params.require(:gene).permit(:drug_page, :disease_page, :name, :source, :description, :uniprotKB, :ensemblID, :entrezID, :pharmGkbID, :drugbankTargetID)
  end
end

app/helpers/genes_helper.rb
module GenesHelper
  def arel_for_gene(_filter)
    # t = Gene.arel_table
    #
    # r = t['gene_id'].eq(0)
    # r = r.or(t[:name].matches("%#{filter}%"))
    # r = r.or(t[:description].matches("%#{filter}%"))
    # r = r.or(t[:uniprotKB].matches("%#{filter}%"))
    # r = r.or(t[:entrezid].eq("#{filter}"))

    # Gene.__elasticsearch__.search(query: { match: { name: 'filter' } }).records
    Gene.where('id = 2')
  end
end

app/views/genes/_form.html.erb
<%= form_for(@gene) do |f| %>
  <% if @gene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gene.errors.count, "error") %> prohibited this gene from being saved:</h2>

      <ul>
      <% @gene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :desctiption %><br>
    <%= f.text_area :desctiption %>
  </div>
  <div class="field">
    <%= f.label :uniprotKB %><br>
    <%= f.text_field :uniprotKB %>
  </div>
  <div class="field">
    <%= f.label :ensemblID %><br>
    <%= f.text_field :ensemblID %>
  </div>
  <div class="field">
    <%= f.label :entrezID %><br>
    <%= f.number_field :entrezID %>
  </div>
  <div class="field">
    <%= f.label :pharmGkbID %><br>
    <%= f.text_field :pharmGkbID %>
  </div>
  <div class="field">
    <%= f.label :drugbankTargetID %><br>
    <%= f.text_field :drugbankTargetID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genes/_gene.haml
%tr
  %td.name
    = link_to(gene.name, gene_path(gene))
  %td= gene['description']
  %td= attr_link(:uniprot, gene)
  %td= attr_link(:ensembl, gene)
  %td= attr_link(:entrez, gene)
  %td= attr_link(:pharmgkb, gene)
  %td= gene['source']
  - if gene.ld?
    %td
      = render 'common/pmids', locals: {pmids: gene.pmids}
    %td
      = render 'common/curated', locals: {status: gene.curated? }

app/views/genes/_gene.html.haml
.jarviswidget.jarviswidget-color-blueDark{:role => 'widget', :id => "wid-id-#{gene.id}" }
  %header{ role: 'heading' }
    %h2{ 'style' => 'padding-right: 30px'}
      = gene['entrezID']

    %ul.nav.nav-tabs.pull-left.in
      %li.active
        %a{ 'data-toggle' => 'tab' , 'href' => "#hr1-#{gene.id}"}
          General
      %li
        %a{ 'data-toggle' => 'tab' , 'href' => "#hr2-#{gene.id}"}
          Diseases
          = "(#{gene.diseases.count})"

  %div{ role: 'content'}
    .widget-body
      .tab-content
        .tab-pane.active{ :id => "hr1-#{gene.id}"}
          %table.table.table-bordered
            %tbody
              %tr
                %td
                  Name
                %td= gene['name']
              %tr
                %td
                  Description
                %td= gene['description']
        .tab-pane{ :id => "hr2-#{gene.id}" }
          %table.table.table-bordered
            %thead
              %tr
                %th
                  Name
                %th
                  Alt. names
                %th
                  Source
            %tbody
              - gene.diseases.each do |g|
                %tr
                  %td= g.name
                  %td= g['alt_names']
                  %td= g.source

app/views/genes/_list.haml
- unless smart_listing.empty?
  %table.table.table-striped
    %thead
      %th.col-md-3= "Name"
      %th.col-md-4= "Description"
      %th.col-md-1= "Uniprot"
      %th.col-md-1= "Ensebml"
      %th.col-md-1= "Entrez"
      %th.col-md-1= "PharmGkb"
      %th.col-md-1= "Source"
    %tbody
      - smart_listing.collection.each do |gene|
        = render gene

  -# Render nice pagination links fitted for Bootstrap 3 by default
  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
- else
  %i.fa.fa-frown-o.fa-5x

app/views/genes/_smart_list.haml
= smart_listing_render :genes

app/views/genes/_smart_list_search_form.haml
= smart_listing_controls_for(:genes, {class: "form-inline text-right"}) do
  .form-group.filter.input-append
    = text_field_tag :genes_filter, '', class: "search form-control", 
                              placeholder: "Search...", autocomplete: :off

app/views/genes/_smart_list_with_search.haml
= render 'genes/smart_list_search_form'
= render 'genes/smart_list'

app/views/genes/edit.html.erb
<h1>Editing gene</h1>

<%= render 'form' %>

<%= link_to 'Show', @gene %> |
<%= link_to 'Back', genes_path %>

app/views/genes/index.haml
= render 'genes/smart_list_with_search'

app/views/genes/index.html.erb
<h1>Listing genes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Source</th>
      <th>Desctiption</th>
      <th>Uniprotkb</th>
      <th>Ensemblid</th>
      <th>Entrezid</th>
      <th>Pharmgkbid</th>
      <th>Drugbanktargetid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @genes.each do |gene| %>
      <tr>
        <td><%= gene.name %></td>
        <td><%= gene.source %></td>
        <td><%= gene.desctiption %></td>
        <td><%= gene.uniprotKB %></td>
        <td><%= gene.ensemblID %></td>
        <td><%= gene.entrezID %></td>
        <td><%= gene.pharmGkbID %></td>
        <td><%= gene.drugbankTargetID %></td>
        <td><%= link_to 'Show', gene %></td>
        <td><%= link_to 'Edit', edit_gene_path(gene) %></td>
        <td><%= link_to 'Destroy', gene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gene', new_gene_path %>

app/views/genes/index.js.erb
<%= smart_listing_update :genes %>

app/views/genes/new.html.erb
<h1>New gene</h1>

<%= render 'form' %>

<%= link_to 'Back', genes_path %>

app/views/genes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gene.name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @gene.source %>
</p>

<p>
  <strong>Desctiption:</strong>
  <%= @gene.desctiption %>
</p>

<p>
  <strong>Uniprotkb:</strong>
  <%= @gene.uniprotKB %>
</p>

<p>
  <strong>Ensemblid:</strong>
  <%= @gene.ensemblID %>
</p>

<p>
  <strong>Entrezid:</strong>
  <%= @gene.entrezID %>
</p>

<p>
  <strong>Pharmgkbid:</strong>
  <%= @gene.pharmGkbID %>
</p>

<p>
  <strong>Drugbanktargetid:</strong>
  <%= @gene.drugbankTargetID %>
</p>

<%= link_to 'Edit', edit_gene_path(@gene) %> |
<%= link_to 'Back', genes_path %>

app/views/genes/show.html.haml
%p#notice= notice

%h1.center
  Gene

%table.table.table-bordered.table-responsive.table-striped.drug-desc
  %tr
    %td
      %b
        Name
    %td= @gene.name

  %tr
    %td
      %b
        Source
    %td= @gene.source

  %tr
    %td
      %b
        Description
    %td= @gene.description

  %tr
    %td
      %b
        Uniprotkb
    %td= attr_link(:uniprot, @gene)

  %tr
    %td
      %b
        Ensemblid
    %td= attr_link(:ensembl, @gene)

  %tr
    %td
      %b
        Entrezid
    %td= attr_link(:entrez, @gene)

  %tr
    %td
      %b
        Pharmgkbid
    %td= attr_link(:pharmgkb, @gene)

= render 'diseases/smart_list_with_search'