config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'searches#index'

  resources :searches

  resources :drugs do
    resources :diseases
    resources :genes
  end
  resources :diseases do
    resources :genes
    resources :drugs
  end
  resources :genes do
    resources :diseases
    resources :drugs
  end
end

app/views/common/_tabs.haml
%ul.nav.nav-tabs
  - unless genes.nil?
    %li{class: "#{'not-empty' if genes.count > 0}"}
      %a{href: '#genes', 'data-toggle' => 'tab'}
        Genes
        = "(#{genes.count})"
  - unless drugs.nil?
    %li{class: "#{'not-empty' if drugs.count > 0}"}
      %a{href: '#drugs', 'data-toggle' => 'tab'}
        Drugs
        = "(#{drugs.count})"
  - unless diseases.nil?
    %li{class: "#{'not-empty' if diseases.count > 0}"}
      %a{href: '#diseases', 'data-toggle' => 'tab'}
        Diseases
        = "(#{diseases.count})"

.tab-content
  - unless genes.nil?
    #genes.tab-pane.fade
      - if genes.empty?
        %i.fa.fa-frown-o.fa-5x
      - else
        - if params[:controller] == 'drugs'
          .tsv-link
            = link_to drug_genes_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        - elsif params[:controller] == 'diseases'
          .tsv-link
            = link_to disease_genes_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        = render partial: 'genes/genes', object: genes, locals: {pmids: pmids}

  - unless drugs.nil?
    #drugs.tab-pane.fade
      - if drugs.empty?
        %i.fa.fa-frown-o.fa-5x
      - else
        - if params[:controller] == 'genes'
          .tsv-link
            = link_to gene_drugs_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        - elsif params[:controller] == 'diseases'
          .tsv-link
            = link_to disease_drugs_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        = render partial: 'drugs/drugs', object: drugs, locals: {pmids: pmids}

  - unless diseases.nil?
    #diseases.tab-pane.fade
      - if diseases.empty?
        %i.fa.fa-frown-o.fa-5x
      - else
        - if params[:controller] == 'genes'
          .tsv-link
            = link_to gene_diseases_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        - elsif params[:controller] == 'drugs'
          .tsv-link
            = link_to drug_diseases_path(params[:id], format: 'tsv') do
              %i.fa.fa-download
        = render partial: 'diseases/diseases', object: diseases, locals: {pmids: pmids}